name: session6
version: '1.0'
main: me.pm7.session6.Session6
api-version: '1.21'
commands:
  stormdifficulty:
    description: for admin use ^w^
  startwildcard:
    description: for admin use :3
  raisetheroof:
    description: for admin use >w<
  stopwildcard:
    description: for admin use OwO