name: BlockStorm
version: '1.01'
main: me.pm7.blockstorm.BlockStorm
api-version: '1.21'
commands:
  stormsettings:
    description: Opens the settings menu for the plugin
  startstorm:
    description: Starts the storm
  setspawnheight:
    description: Sets the height at which the pieces spawn at
  stopstorm:
    description: Stops the storm