name: session6
version: '1.0'
main: me.pm7.session6.Session6
api-version: '1.21'
commands:
  test:
    description: owo
  stormdifficulty:
    description: for admin use ^w^
  startwildcard:
    description: for admin use :3
  thatonething:
    description: honestly idk man
  raisetheroof:
    description: for admin use >w<
  stopwildcard:
    description: for admin use UwU
  stopthething:
    description: for admin use OwO