name: storm
version: '1.0'
main: me.pm7.storm.Storm
api-version: '1.21'
commands:
  stormsettings:
    description: Opens the settings menu for the plugin
  startstorm:
    description: Starts the storm
  setstormheight:
    description: Sets the height at which the pieces spawn at
  stopstorm:
    description: Stops the storm