name: session6
version: '1.0'
main: me.pm7.session6.Session6
api-version: '1.21'
commands:
  carddifficulty:
    description: for admin use ^w^
  startwildcard:
    description: for admin use :3
  raisetheroof:
    description: for admin use >w<
  stopwildcard:
    description: for admin use OwO
  think:
    description: for thinking
  fren:
    description: for... something
  volcanicroc:
    description: surprisingly, not for piffin
  fernace:
    description: idk at this point