name: session6
version: '1.0'
main: me.pm7.storm.Storm
api-version: '1.21'
commands:
  stormdifficulty:
    description: for admin use ^w^
  startstorm:
    description: for admin use :3
  raisetheroof:
    description: for admin use >w<
  stopstorm:
    description: for admin use OwO